# Generated by Django 5.0.2 on 2024-02-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='username',
            field=models.CharField(default=1, max_length=56, unique=True),
            preserve_default=False,
        ),
    ]
